### PR TITLE
use @clusterws/uws instead of uws

### PR DESCRIPTION
**Pull request by G-Ray**
uws does not compile against node 10, is not maintained on npmjs, and I'm unable to find the sources.

If I understand correctly, https://github.com/uNetworking/uWebSockets used to provide nodeJS bindings, but not anymore.

So this PR replaces the "old" uws with https://github.com/ClusterWS/uWS instead.

### CODE REVIEW

**Comment by soyuka** [comment]
Just saw your update, thanks I would prefer to use ws instead then but the test suite doesn't pass there :/

see https://github.com/soyuka/signalhubws/pull/6

**Comment by soyuka** [comment]
Can you cherry pick a046dbd34f3d7d178c21eac4321f0ef0b5011515?

**Comment by G-Ray** [comment]
I tried with ws and encountered the same issue. Ok, I cherry picked a046dbd, you can review once again

**Comment by soyuka** [comment]
Nice thanks! let's merge this one for now I'll open an issue on the `ws` repository, I think it'll be better to use `ws` then a fork of `uws` WDYT?

**Comment by soyuka** [comment]
Patched in 1.0.5, thanks for the report.

**Pull request merged**
